version: "3.9"

services:
  impulse-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: impulse-server
    environment:
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_SECRET_KEY: ${BINANCE_SECRET_KEY}
    ports:
      - "50051:50051"

  impulse-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: impulse-client
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_TOKEN_SECOND: ${TELEGRAM_BOT_TOKEN_SECOND}
      DB: ${DB}
      POSTMARK_TOKEN: ${POSTMARK_TOKEN}
    depends_on:
      - impulse-server
      - mongo

  mongo:
    image: mongo
    volumes:
      - ~/db/mongo:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo
    command: /bin/bash -c "sleep 20; /docker-entrypoint.sh"