# Dockerfile.server

FROM --platform=linux/amd64 golang:1.20.3-alpine
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o binance-server ./server/cmd/binance-server

CMD ["./binance-server"]