# Dockerfile.client

FROM --platform=linux/amd64 golang:1.17-alpine
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o binance-client ./client/cmd/binance-client

CMD ["./binance-client"]