# Dockerfile.client

FROM --platform=linux/amd64 golang:1.20.3-alpine3.17 AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o binance-client ./client/cmd/binance-client && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

FROM --platform=linux/amd64 alpine:3.17
COPY --from=build /app/binance-client /bin/binance-client

CMD ["binance-client"]