// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: binance.proto

package grpcbinance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_binance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_binance_proto_rawDescGZIP(), []int{0}
}

type USDTPricesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prices []*USDTPrice `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
}

func (x *USDTPricesResponse) Reset() {
	*x = USDTPricesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USDTPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USDTPricesResponse) ProtoMessage() {}

func (x *USDTPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USDTPricesResponse.ProtoReflect.Descriptor instead.
func (*USDTPricesResponse) Descriptor() ([]byte, []int) {
	return file_binance_proto_rawDescGZIP(), []int{1}
}

func (x *USDTPricesResponse) GetPrices() []*USDTPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

type USDTPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price  float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *USDTPrice) Reset() {
	*x = USDTPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USDTPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USDTPrice) ProtoMessage() {}

func (x *USDTPrice) ProtoReflect() protoreflect.Message {
	mi := &file_binance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USDTPrice.ProtoReflect.Descriptor instead.
func (*USDTPrice) Descriptor() ([]byte, []int) {
	return file_binance_proto_rawDescGZIP(), []int{2}
}

func (x *USDTPrice) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *USDTPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ChangePercentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangePercents []*ChangePercent `protobuf:"bytes,1,rep,name=change_percents,json=changePercents,proto3" json:"change_percents,omitempty"`
}

func (x *ChangePercentResponse) Reset() {
	*x = ChangePercentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePercentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePercentResponse) ProtoMessage() {}

func (x *ChangePercentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePercentResponse.ProtoReflect.Descriptor instead.
func (*ChangePercentResponse) Descriptor() ([]byte, []int) {
	return file_binance_proto_rawDescGZIP(), []int{3}
}

func (x *ChangePercentResponse) GetChangePercents() []*ChangePercent {
	if x != nil {
		return x.ChangePercents
	}
	return nil
}

type ChangePercent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol        string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ChangePercent float64 `protobuf:"fixed64,2,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
}

func (x *ChangePercent) Reset() {
	*x = ChangePercent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePercent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePercent) ProtoMessage() {}

func (x *ChangePercent) ProtoReflect() protoreflect.Message {
	mi := &file_binance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePercent.ProtoReflect.Descriptor instead.
func (*ChangePercent) Descriptor() ([]byte, []int) {
	return file_binance_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePercent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ChangePercent) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

var File_binance_proto protoreflect.FileDescriptor

var file_binance_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x40, 0x0a, 0x12, 0x55, 0x53, 0x44, 0x54, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x2e, 0x55, 0x53, 0x44, 0x54, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x06, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x09, 0x55, 0x53, 0x44, 0x54, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x58,
	0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4e, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x32, 0x95, 0x01, 0x0a, 0x0e, 0x42, 0x69, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x55, 0x53, 0x44, 0x54, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x0e, 0x2e, 0x62,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x62,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x55, 0x53, 0x44, 0x54, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x32, 0x34, 0x68, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1e, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x67, 0x6f, 0x70, 0x61, 0x6e, 0x6b, 0x6f, 0x76, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_binance_proto_rawDescOnce sync.Once
	file_binance_proto_rawDescData = file_binance_proto_rawDesc
)

func file_binance_proto_rawDescGZIP() []byte {
	file_binance_proto_rawDescOnce.Do(func() {
		file_binance_proto_rawDescData = protoimpl.X.CompressGZIP(file_binance_proto_rawDescData)
	})
	return file_binance_proto_rawDescData
}

var file_binance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_binance_proto_goTypes = []interface{}{
	(*Empty)(nil),                 // 0: binance.Empty
	(*USDTPricesResponse)(nil),    // 1: binance.USDTPricesResponse
	(*USDTPrice)(nil),             // 2: binance.USDTPrice
	(*ChangePercentResponse)(nil), // 3: binance.ChangePercentResponse
	(*ChangePercent)(nil),         // 4: binance.ChangePercent
}
var file_binance_proto_depIdxs = []int32{
	2, // 0: binance.USDTPricesResponse.prices:type_name -> binance.USDTPrice
	4, // 1: binance.ChangePercentResponse.change_percents:type_name -> binance.ChangePercent
	0, // 2: binance.BinanceService.GetUSDTPrices:input_type -> binance.Empty
	0, // 3: binance.BinanceService.Get24hChangePercent:input_type -> binance.Empty
	1, // 4: binance.BinanceService.GetUSDTPrices:output_type -> binance.USDTPricesResponse
	3, // 5: binance.BinanceService.Get24hChangePercent:output_type -> binance.ChangePercentResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_binance_proto_init() }
func file_binance_proto_init() {
	if File_binance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_binance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USDTPricesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USDTPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangePercentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangePercent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_binance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_binance_proto_goTypes,
		DependencyIndexes: file_binance_proto_depIdxs,
		MessageInfos:      file_binance_proto_msgTypes,
	}.Build()
	File_binance_proto = out.File
	file_binance_proto_rawDesc = nil
	file_binance_proto_goTypes = nil
	file_binance_proto_depIdxs = nil
}
