apiVersion: apps/v1
kind: Deployment
metadata:
  name: impulse-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impulse-client
  template:
    metadata:
      labels:
        app: impulse-client
    spec:
      serviceAccountName: binance-app-sa
      containers:
        - name: impulse-client
          image: 174907374174.dkr.ecr.eu-west-2.amazonaws.com/impulse-client:latest
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets-manager"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: impulse-client-config